#!/usr/bin/env sh

whitelist="\
/home/git \
/disk/Career \
/disk/Media \
~/Downloads \
"

blacklist="node_modules\
|/package.json\
|/\.git\
|/\.gitignore\
|LICENSE\
|README.md\
|\.icons\
|\.themes\
|wallpapers/\
|fonts/\
|voidrice/\
|Career/\
|Downloads/\
|Media/\
"

maxDepth=7

find -L $whitelist -maxdepth $maxDepth |
   grep -Ev $blacklist \
      > "$SEARCH_LIST"
