#!/usr/bin/env sh

whitelist="\
/home/$USER/Downloads \
/home/git/own \
/disk/Career/FE_Exam/practice \
/disk/Media \
/disk/Phone \
"

blacklist="node_modules\
|/package.json\
|/\.git\
|/\.gitignore\
|LICENSE\
|README.md\
|\.icons\
|\.themes\
|wallpapers/\
|fonts/\
|Downloads/\
|Media/\
|Linux/\
|Phone/\
|dwm/\
|sent/\
"

maxDepth=7

find -L $whitelist -maxdepth $maxDepth |
   grep -Ev $blacklist \
      > "$SEARCH_LIST"
