#!/usr/bin/env sh

ignore="node_modules\
|\.icons\
|voidrice\
|\.git\
|\.themes\
|LICENSE\
|README.md\
|wallpapers\
"

grep -v "^#" ~/.config/shortcutrc |
   xargs -I% find -L % -maxdepth 5 |
   grep -Ev "$ignore" \
   > "$SEARCH_LIST"
