#!/usr/bin/env sh

FILE="$1"
HEIGHT="$2"
WIDTH=80

HIGHLIGHT_SIZE_MAX=262143 # 256KiB
HIGHLIGHT_STYLE='pablo'

case $(file --dereference --brief --mime-type "$FILE") in

   image/*)
      chafa --fill=block --symbols=block --colors=256 --size="$WIDTH"x"$HEIGHT"
      "$FILE" || exit 1
      ;;

   text/* | */xml)

      if [ "$(stat --printf='%s' -- "${FILE_PATH}")" -gt "${HIGHLIGHT_SIZE_MAX}" ]; then
         exit 2
      fi
      if [ "$(tput colors)" -ge 256 ]; then
         local highlight_format='xterm256'
      else
         local highlight_format='ansi'
      fi

      highlight \
         --replace-tabs=3 \
         --out-format="${highlight_format}" \
         --style=pablo \
         --force -- "$FILE"

      # highlight --force --out-format=ansi -- "$FILE"

      ;;

   */pdf)
      pdftotext -l 10 -nopgbrk -q -- "$FILE" -
      ;;

   *)
      file --brief "$FILE"
      ;;
esac
