#!/usr/bin/env sh

[ "$1" = -s ] &&
   cp "$(find -L ~/.local/share/wallpapers -type f | shuf -n1)" "$WALL" ||
   cp "$1" "$WALL" && cp "$1" "$GIT"/own/magpie/wallpapers

feh --no-fehbg --bg-scale "$WALL"
