#!/bin/sh

rm -r fifo
mkfifo fifo
exec 3<> fifo

while :; do
    echo yo >&3
    sleep 3
done &

cat <&3

# grep -Pzo \
#     '(http|https)://[a-zA-Z0-9+&@#/%?=~_|!:,.;-]*\n*[a-zA-Z0-9+&@#/%?=~_|!:,.;-]*' /tmp/tb |
#     tr -d '\n' |
#     sed -e 's/http/\nhttp/g' -e 's/$/\n/' |
#     sed '1d' | sort | uniq

# grep -Pzo \
# '(http|https)://[a-zA-Z0-9+&@#/%?=~_|!:,.;-]*\n*[a-zA-Z0-9+&@#/%?=~_|!:,.;-]*' /tmp/tb
# tr -d '\n'

# ns -t 5000 $$
# sleep 15 &

# IFS=-"-"
# first=$1
# second=$2
# echo "$first $second"
# IFS=$SAVEIFS

# [ -p /tmp/toyfifo ] || mkfifo /tmp/toyfifo
# exec 3<> /tmp/toyfifo

# echo yo >&3

# while read -r line; do
#     echo $line
# done <&3

# rm -r fifo
# mkfifo fifo
# exec 3<> fifo

# while :; do
#     echo yo >&3
#     sleep 3
# done

# cat < fifo
# exec 3< fifo # open fifo for reading
# exec cat fifo | nl

# tail -n +1 -f pipe
