#!/usr/bin/env sh

toggleOn(){
   doas killall yabar
   bspc config top_padding	0
   bspc desktop -l monocle
}

toggleOff(){
   yabar &
   bspc config top_padding	35
   bspc desktop -l tiled
}

pidof yabar && toggleOn || toggleOff

# pidof yabar && doas killall yabar || yabar &
# bspc node -t \~fullscreen

