#!/usr/bin/env sh

flag=/tmp/dunst

[ -f "$flag" ] && {
   notify-send -t 1000 -i "$ICONS"/dnd.png 'Do not disturb'
   sleep 2
   killall -SIGUSR1 dunst
   rm -f $flag
} || {
   killall -SIGUSR2 dunst
   touch $flag
   sleep 1
   notify-send -t 1000 -i "$ICONS"/bell.png 'Disturb all you want'
}

# pidof notification-daemon &&
#    notify-send -t 1000 -i ~/.icons/system/dnd.png 'Do not disturb' &&
#    sleep 1 &&
#    killall notification-daemon &&
#    exit

# notification-daemon &
# sleep 0.5
# notify-send -t 1000 -i ~/.icons/system/bell.png 'Disturb all you want'
