#!/usr/bin/env sh

ddm=/tmp/ddm

if [ -f "$ddm" ]; then
   rm -f "$ddm"
   killall -SIGUSR2 dunst
   sleep 1
   notify-send -t 1000 -i "$ICONS"/bell.png 'Disturb all you want'
else
   touch "$ddm"
   notify-send -t 1000 -i "$ICONS"/dnd.png 'Do not disturb'
   sleep 2
   killall -SIGUSR1 dunst
fi

refresh-block 3
# refresh-block -n

# pidof notification-daemon &&
#    notify-send -t 1000 -i ~/.icons/system/dnd.png 'Do not disturb' &&
#    sleep 1 &&
#    killall notification-daemon &&
#    exit

# notification-daemon &
# sleep 0.5
# notify-send -t 1000 -i ~/.icons/system/bell.png 'Disturb all you want'
