#!/usr/bin/env bash
#
# Torque2 - minimal tui for transmission-daemon.

refresh() {
    printf '\e[?7l\e[?25l\e[2J\e[H'
    shopt -s checkwinsize; (:;:)
    [ -z "$LINES" ] && set -- "$(stty size)" && LINES=$1 && COLUMNS=$2
    ((l=(LINES-2)/3))
}

status() { printf '\e[2m\e[%s;H%s\e[m' "$((LINES-1))" "$1"; }

get_torrents() {
    IFS=$'\n' read -d "" -ra t < <(transmission-remote -l)
    unset 't[0]' 't[-1]' 2>/dev/null

    t=("${t[@]//[0-9] [a-z][a-z][a-z]?/.}")
    t=("${t[@]//Up & Down/Active}")
    t=("${t[@]//Downloading/Active}")
    t=("${t[@]//     None/0 MB}")

    for((i=${k:=0};i<(l=l>${#t[@]}?${#t[@]}:l);i++));{ t_print "${t[i]/n\/a/0}";}
    status "[s]tart [p]ause [r]emove [m]agnet ($l/${#t[@]})"$'\e[H'
}

t_print() {
    IFS=" %" read -r num perc have unit _ up down _ stat name <<< "$1"

    ((size=perc!=0?${have/.*}*100/perc:0,c=perc==100?33271340:31000000))

    printf '\e[K\e[2m%s\e[m \e[1m\e[%s%b%s\e[m\n' \
           "$num:" "${c:0:2}m" "\\u${c:2:4}\\${c:6}" "$name"
    printf '\e[K\e7%s\e8\e[14C%s\e8\e[32C%s\e8\e[42C%s\e8\e[52C%s\n\e[K\n' \
           "   $stat: " "$have / $size $unit" "(${perc}%)" "⇣ $down" "⇡ $up"
}

prompt() {
    send() { transmission-remote "$@" >/dev/null; }
    status $'\e[B\e[?25h'
    case "$1" in
        s) echo "start torrent: #"; read -r; send -t "$REPLY" -s ;;
        p) echo "pause torrent: #"; read -r;  send -t "$REPLY" -S ;;
        r) echo "remove torrent: #"; read -r; send -t "$REPLY" -r; k=0 ;;
        m) echo "load magnet: "; read -r; send -a "$REPLY" ;;
    esac
    refresh && printf '\e[?25l\e[H'
}

getkey() {
    stty -icanon -echo
    dd bs=1 count=1 2> /dev/null
    stty icanon echo
}

refresh
while :; do
    get_torrents
    prompt "$(getkey)"
done
