#!/usr/bin/env sh

notify-send -t 3000 -i "$ICONS"/github.png "Time to update git reopos"

for dir in /home/git/others/*/; do
    [ -d "$dir" ] && git -C "$dir" pull ||
        succeed=0
done

[ "$succeed" = 1 ] &&
    notify-send -t 3000 -i "$ICONS"/github.png "Done updating git repos" ||
    notify-send -t 3000 -i $ICONS/critical.png "Git update failled"
