#!/usr/bin/env sh

dirs="\
$GIT/own/magpie \
$GIT/own/private \
"

sync() {
   cp -frs -t ~ \
      "$GIT"/own/magpie/. \
      "$GIT"/own/private/. \
   # doas -- find ~ -xtype l -delete
   # doas -- find ~ -type d -empty -delete
}

inotifywait -m -r -e create,moved_to $dirs |
   while read -r event; do
      sync
   done

