#!/usr/bin/env sh

nodeList=/tmp/$(bspc query -D -d)
[ "$STATUS_BAR" ] || export STATUS_BAR=polybar

toggle_fs_on() {
   killall $STATUS_BAR
   bspc config top_padding 0
   bspc query -N -n .local.leaf.!focused.!hidden | tee "$nodeList"
   bspc desktop -l monocle
}

toggle_fs_off() {
   $STATUS_BAR &
   bspc config top_padding 35
   bspc desktop -l tiled
}

case $1 in
   --navigate)
      if [ "$2" = "next" ]; then
         bspc node -f next.local && exit 1
      else
         bspc node -f prev.local && exit 1
      fi

      [ ! -f "$nodeList" ] && exit 1
      [ "$(wc -l < "$nodeList")" = 0 ] && exit 1

      if [ "$2" = "next" ]; then
         head -1 "$nodeList" | xargs -I% bspc node % -g hidden
         sed -i '1d' "$nodeList"
         bspc query -N -n >> "$nodeList"
      else
         tail -1 "$nodeList" | xargs -I% bspc node % -g hidden
         sed -i '$d' "$nodeList"
         bspc query -N -n >> "$nodeList"
      fi

      bspc node -g hidden

      ;;

   --toggle)

      if [ "$2" = "fullscreen" ]; then
         if pidof yabar; then toggle_fs_on; else toggle_fs_off; fi
         bspc node -n biggest.local
         cat "$nodeList" | xargs -I% bspc node % -g hidden
      else

         [ "$(bspc wm -g | cut -d: -f7)" = "LT" ] &&
            bspc query -N -n .local.leaf.!focused.!hidden | tee "$nodeList"

         bspc desktop -l next
         bspc node -n biggest.local
         cat "$nodeList" | xargs -I% bspc node % -g hidden

      fi

      ;;

   --close)
      bspc node -c
      if [ "$(wc -l < "$nodeList")" -gt 0 ]; then
         tail -1 "$nodeList" | xargs -I% bspc node % -g hidden
         sed -i '$d' "$nodeList"
      fi
      ;;

   *) : ;;

esac
