#!/usr/bin/env sh

nodeList=/tmp/$(bspc query -D -d)
statusbar=yabar

toggleOn(){
   doas killall $statusbar
   bspc config top_padding 0
   bspc query -N -n .local.leaf.!focused.!hidden | tee "$nodeList"
}

toggleOff(){
   $statusbar &
   bspc config top_padding 35
}

pidof yabar && toggleOn || toggleOff

bspc node -t ~fullscreen
bspc node -n biggest.local
cat "$nodeList" | xargs -I% bspc node % -g hidden
