#!/usr/bin/env sh

nodeList=/tmp/$(bspc query -D -d)

[ "$(bspc wm -g | cut -d: -f7)" = "LT" ] &&
   bspc query -N -n .local.leaf.!focused.!hidden | tee "$nodeList"

bspc node -n biggest.local
bspc desktop -l next
cat "$nodeList" | xargs -I% bspc node % -g hidden

# notify-send "$(bspc query -N -n .local.leaf)"

# bspc node "$(cat "$nodeList")" -g hidden


# if [ "$(bspc wm -g | cut -d: -f7)" = "LM" ]; then
   # :
   # bspc desktop -l tiled

   # notify-send -t 500 \
   #    "$(cat "$nodeList")"

   # bspc node "$(cat "$nodeList")" -g hidden

   # bspc query -N -n .local.hidden | xargs -I% bspc node % -g hidden
   # bspc node "$(cat "$nodeList")" -g hidden
   # cat "nodeList" | xargs -I% bspc node % -g hidden
   # : > "$nodeList"

# else
   # :
   # bspc desktop -l monocle
   # bspc node -n biggest.local

   # notify-send -t 500 \
   #    "$(bspc query -N -n .local.leaf.!focused)"
   # bspc query -N -n .local.leaf.!focused.!hidden | tee "$nodeList"
   # bspc node "$(cat "$nodeList")" -g hidden

   # bspc query -N -n .local.!hidden -d | xargs -I% bspc node % -g hidden
   # bspc query -N -n .leaf.!focused -d | tee "$nodeList"
   # bspc query -N -n .leaf.!focused.!hidden -d | tee "$nodeList"
   # bspc node "$(cat "$nodeList")" -g hidden
   # cat "nodeList" | xargs -I% bspc node % -g hidden
# fi


# notify-send "$(bspc query -N -n .leaf.!focused.!hidden -d)"

# bspc desktop -l next

# [ -s "$nodeList" ] && {
# bspc node "$(cat "$nodeList")" -g hidden
# : > "$nodeList"
# } || {
# bspc query -N -n .leaf.!focused.!hidden -d | tee "$nodeList"
# bspc query -N -n .tiled.!focused.!hidden -d | tee "$nodeList"
# bspc node "$(cat "$nodeList")" -g hidden
# }
