#!/usr/bin/env sh

# connected ||
#    {
#       notify-send -t 3000 -i $ICONS/disconnected.png "Disconnected"
#       exit 1
#    }

# notify-send -t 3000 -i $ICONS/gitlab.png "Syncing git repos"

for dir in "$GIT"/own/*/; do
    [ -d "$dir" ] && {
        cd "$dir" || exit 1
        # git pull
        git add .

        # case $dir in
        #     *bolt*) touch test;;
        # esac

        # [ "$dir" =~ *"bolt"* ] && touch test
        # git commit -m "Complete overhaul & added a Makefile" &&
        # git push && continue

        # git status --porcelain &&
        #     git commit -m "$(rofi -dmenu -i -p "$(pwd | rev | cut -d/ -f1 | rev)")" &&
        #     git push

        git commit -m "update" && git push

    }
done

notify-send -t 3000 -i $ICONS/gitlab.png "Done syncing git repos"
