#!/usr/bin/env sh

# connected ||
#    {
#       notify-send -t 3000 -i $ICONS/disconnected.png "Disconnected"
#       exit 1
#    }

# notify-send -t 3000 -i $ICONS/gitlab.png "Syncing git repos"

for dir in "$GIT"/own/*/; do
    [ -d "$dir" ] && {
        cd "$dir" || exit 1
        # git pull
        git add .
        [ -z "$(git status --porcelain)" ] && exit 1
        git commit -m "$(rofi -dmenu -i -p "$(pwd | rev | cut -d/ -f1 | rev)")" &&
            git push
        # git commit -m "update" && git push
    }
done

notify-send -t 3000 -i $ICONS/gitlab.png "Done syncing git repos"
