#!/usr/bin/env sh

ICONS=~/.icons/system

path=~/.local/bin
"$path"/misc/connected ||
   {
      notify-send -t 3000 -i $ICONS/disconnected.png "Disconnected"
      exit 1
   }

CALCURSE_CALDAV_PASSWORD=$(gpg -d --batch --passphrase asdlkj ~/.local/share/passwords/salmanabedin@disroot.org.gpg) calcurse-caldav

notify-send -t 3000 -i "$ICONS"/calendar.png "Done syncing calcurse"
