#!/usr/bin/env sh

notify-send -t 3000 -i "$ICONS"/drive.png "Time to Mirror Drive"

sync() {
    for i in "$@"; do
        cd ~/Drive/"$i" || exit 1
        # drive pull -no-prompt
        drive push -no-prompt ||
            notify-send -t 3000 -i "$ICONS"/critical.png "Couldn't sync with Drive!" ||
            exit 1
    done
}

dir="Audio Books"
[ "$1" ] && sync "$@" || sync "$dir"
notify-send -t 3000 -i $ICONS/drive.png "Done Mirroring Drive"
