#!/usr/bin/env sh

ICONS=~/.icons/system
path=~/.local/bin

"$path"/misc/connected ||
   {
      notify-send -t 3000 -i $ICONS/disconnected.png "Disconnected"
      exit 1
   }

mbsync -c ~/.config/isync/mbsyncrc -a 2> /dev/null

unread=$(find ~/.local/share/mail/gmail/INBOX/new/* -type f 2> /dev/null | wc -l)

# [ "$unread" -gt 0 ] && notify-send -t 0 -i "$ICONS/mail.png" "Mail" "You've got $unread new mail!"

[ "$unread" -gt 0 ] && /usr/bin/"$TERMINAL" -e /usr/bin/neomutt &

