#!/usr/bin/env sh

echo yo

# path=$(readlink -f "$0")
# dir="${path%/*}"
# echo $dir

# whitelist="$(cat $dir/whitelist)"

# echo $whitelist

# blacklist="node_modules\
# |/package.json\
# |/\.git\
# |/\.gitignore\
# |LICENSE\
# |README.md\
# |\.icons\
# |\.themes\
# |wallpapers/\
# |fonts/\
# |Downloads/\
# |Media/\
# |Linux/\
# |dwm/\
# |sent/\
# "

# maxDepth=7

# genList(){
#    find -L $whitelist -maxdepth $maxDepth |
#       grep -Ev $blacklist \
#          > "$SEARCH_LIST"
# }

# genList

# inotifywait -m -r -e create,delete,move --format "%e" $whitelist |
#    while read -r event; do
#       genList
#    done

